version: '3'

services:
  v2ray:
    container_name: v2ray
    image: v2ray/official
    restart: unless-stopped
    command: v2ray -config=/etc/v2ray/config.json
    expose:
      - "19487" # v2ray port
    ports:
      - "19487:19487" # v2ray port
      - "19487:19487/udp" # v2ray port
    volumes:
      - ./v2ray_logs:/var/log/v2ray/
      - ./config.json:/etc/v2ray/config.json:ro
    environment:
      - "VIRTUAL_HOST=app.etshfw.cn" #域名
      - "VIRTUAL_PORT=19487"
      - "LETSENCRYPT_HOST=app.etshfw.cn" #域名
      - "LETSENCRYPT_EMAIL=1003451387@qq.com" #邮箱
  nginx:
    image: nginx
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/vhost.d:/etc/nginx/vhost.d
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/certs:/etc/nginx/certs:ro
    ports:
      - 443:443
      - 80:80
  nginx-gen:
    image: jwilder/docker-gen
    command: -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    container_name: nginx-gen
    restart: unless-stopped
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/vhost.d:/etc/nginx/vhost.d
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-letsencrypt
    restart: unless-stopped
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/vhost.d:/etc/nginx/vhost.d
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      NGINX_DOCKER_GEN_CONTAINER: "nginx-gen"
      NGINX_PROXY_CONTAINER: "nginx"
